"""add claim fields

Revision ID: 18041e0ee441
Revises: 
Create Date: 2026-04-03 10:19:10.802862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18041e0ee441'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payouts_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_community_pools_id'), table_name='community_pools')
    op.drop_table('community_pools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_pools',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('zone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('total_funds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('community_pools_pkey'))
    )
    op.create_index(op.f('ix_community_pools_id'), 'community_pools', ['id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('payouts_pkey'))
    )
    op.create_index(op.f('ix_payouts_id'), 'payouts', ['id'], unique=False)
    # ### end Alembic commands ###
