"""add columns

Revision ID: 3fa8df7d759b
Revises: a370b81e9cfe
Create Date: 2026-04-04 10:25:34.524122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fa8df7d759b'
down_revision: Union[str, Sequence[str], None] = 'a370b81e9cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bank_id'), table_name='user_bank')
    op.drop_table('user_bank')
    op.add_column('claims', sa.Column('risk_level', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('fraud_reason', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('payment_status', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('payment_id', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('claims', sa.Column('payment_provider', sa.String(), nullable=True))
    op.alter_column('claims', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('claims', 'payment_provider')
    op.drop_column('claims', 'payment_method')
    op.drop_column('claims', 'payment_id')
    op.drop_column('claims', 'payment_status')
    op.drop_column('claims', 'fraud_reason')
    op.drop_column('claims', 'risk_level')
    op.create_table('user_bank',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_bank_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_bank_pkey'))
    )
    op.create_index(op.f('ix_user_bank_id'), 'user_bank', ['id'], unique=False)
    # ### end Alembic commands ###
