"""update insurance model

Revision ID: 6c6a32c98248
Revises: ac31ac91b5f3
Create Date: 2026-04-04 18:43:04.354422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c6a32c98248'
down_revision: Union[str, Sequence[str], None] = 'ac31ac91b5f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bank_id'), table_name='user_bank')
    op.drop_table('user_bank')
    op.add_column('insurance', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('insurance', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('insurance', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('insurance', 'plan_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('insurance', 'premium',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('insurance', 'coverage',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('insurance', 'coverage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('insurance', 'premium',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('insurance', 'plan_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('insurance', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('insurance', 'updated_at')
    op.drop_column('insurance', 'created_at')
    op.create_table('user_bank',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_bank_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_bank_pkey'))
    )
    op.create_index(op.f('ix_user_bank_id'), 'user_bank', ['id'], unique=False)
    # ### end Alembic commands ###
