"""add locked_until

Revision ID: a370b81e9cfe
Revises: 18041e0ee441
Create Date: 2026-04-04 09:22:09.182779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a370b81e9cfe'
down_revision: Union[str, Sequence[str], None] = '18041e0ee441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claims', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'claims', 'users', ['user_id'], ['id'])
    op.drop_column('claims', 'reason')
    op.add_column('insurance', sa.Column('locked_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('insurance', 'locked_until')
    op.add_column('claims', sa.Column('reason', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.alter_column('claims', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
