"""add user extra fields

Revision ID: ac31ac91b5f3
Revises: 3fa8df7d759b
Create Date: 2026-04-04 15:28:28.194006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac31ac91b5f3'
down_revision: Union[str, Sequence[str], None] = '3fa8df7d759b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bank_id'), table_name='user_bank')
    op.drop_table('user_bank')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('upi', sa.String(), nullable=True))
    op.add_column('users', sa.Column('bank_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bank_name')
    op.drop_column('users', 'upi')
    op.drop_column('users', 'phone')
    op.create_table('user_bank',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('upi', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_bank_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_bank_pkey'))
    )
    op.create_index(op.f('ix_user_bank_id'), 'user_bank', ['id'], unique=False)
    # ### end Alembic commands ###
